"""expand_synthea_and_agent_models

Revision ID: e24f87f20945
Revises: 6d04204d8b89
Create Date: 2026-09-22 21:58:59.138307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e24f87f20945'
down_revision: Union[str, Sequence[str], None] = '6d04204d8b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('birthdate', sa.String(length=32), nullable=True),
    sa.Column('deathdate', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('race', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('stop_date', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_code'), 'conditions', ['code'], unique=False)
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('stop_date', sa.String(length=32), nullable=True),
    sa.Column('encounter_class', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_id'), 'encounters', ['id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['triage_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_agent_name'), 'agent_traces', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_traces_case_id'), 'agent_traces', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_id'), 'agent_traces', ['id'], unique=False)
    op.create_table('evidence_citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('relevance_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['triage_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_citations_case_id'), 'evidence_citations', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_citations_id'), 'evidence_citations', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_citations_pmid'), 'evidence_citations', ['pmid'], unique=False)
    op.add_column('triage_records', sa.Column('patient_id', sa.String(length=64), nullable=True))
    op.add_column('triage_records', sa.Column('chief_complaint', sa.Text(), nullable=True))
    op.add_column('triage_records', sa.Column('narrative_summary', sa.Text(), nullable=True))
    op.alter_column('triage_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_triage_records_created_at'), 'triage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_triage_records_patient_id'), 'triage_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_triage_records_severity'), 'triage_records', ['severity'], unique=False)
    op.create_index(op.f('ix_triage_records_specialist'), 'triage_records', ['specialist'], unique=False)
    op.create_foreign_key('fk_triage_records_patient_id', 'triage_records', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_triage_records_patient_id', 'triage_records', type_='foreignkey')
    op.drop_index(op.f('ix_triage_records_specialist'), table_name='triage_records')
    op.drop_index(op.f('ix_triage_records_severity'), table_name='triage_records')
    op.drop_index(op.f('ix_triage_records_patient_id'), table_name='triage_records')
    op.drop_index(op.f('ix_triage_records_created_at'), table_name='triage_records')
    op.alter_column('triage_records', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('triage_records', 'narrative_summary')
    op.drop_column('triage_records', 'chief_complaint')
    op.drop_column('triage_records', 'patient_id')
    op.drop_index(op.f('ix_evidence_citations_pmid'), table_name='evidence_citations')
    op.drop_index(op.f('ix_evidence_citations_id'), table_name='evidence_citations')
    op.drop_index(op.f('ix_evidence_citations_case_id'), table_name='evidence_citations')
    op.drop_table('evidence_citations')
    op.drop_index(op.f('ix_agent_traces_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_case_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_agent_name'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_code'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
